project:
  type: website
  output-dir: _site
  preview:
    port: 5678
    browser: true
  render:
    - "!chunks/"
    - "404.qmd"
    - "about.qmd"
    - "blog/index.qmd"
    - "blog/**/*.qmd"
    - "conditional-control.qmd"
    - "custom-questions.qmd"
    - "deployment.qmd"
    - "demos/question-types.qmd"
    - "demos/show-if.qmd"
    - "demos/skip-if.qmd"
    - "demos/conjoint-buttons.qmd"
    - "demos/random-labels.qmd"
    - "demos.qmd"
    - "documentation.qmd"
    - "external-resources.qmd"
    - "faq.qmd"
    - "features.qmd"
    - "fetch-data.qmd"
    - "question-formatting.qmd"
    - "getting-started.qmd"
    - "index.qmd"
    - "installation.qmd"
    - "template.qmd"
    - "password.qmd"
    - "performance.qmd"
    - "question-types.qmd"
    - "reactivity.qmd"
    - "redirect.qmd"
    - "security.qmd"
    - "server-options.qmd"
    - "system-translations.qmd"
    - "store-data.qmd"
    - "survey-components.qmd"
    - "tips.qmd"

website:
  title: surveydown.org
  image: images/logo.ico
  favicon: images/logo.ico
  site-url: https://www.surveydown.org
  repo-url: https://github.com/surveydown/website
  back-to-top-navigation: true
  open-graph:
    locale: es_ES
    site-name: https://surveydown.org
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: images/logo.png
    card-style: summary_large_image
    image-width: 150
    image-height: 150
  page-footer:
    background: dark
    center:
      - text: "Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/jhelvy/jhelvy_quarto' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"

  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: about.qmd   
      - text: "Documentation"
        href: documentation.qmd
      - text: "Features"
        href: features.qmd
      - text: "Demos"
        href: demos.qmd
      - text: "{{< fa brands r-project >}} Package"
        href: https://pkg.surveydown.org/
    right:
      - text: "Blog"
        href: blog/index.qmd
      - text: "FAQ"
        href: faq.qmd
      - icon: github
        href: https://github.com/surveydown-dev/surveydown

  sidebar:
    - title: "Documentation"
      style: "docked"
      background: light
      contents:
        - text: "Documentation"
          href: documentation.qmd
        - text: "Getting Started"
          href: getting-started.qmd
        - text: "Installation"
          href: installation.qmd
        - section: "Reference Manuals"
          contents: 
            - text: "Start with a Template"
              href: template.qmd
            - text: "Survey Components"
              href: survey-components.qmd
            - text: "Question Types"
              href: question-types.qmd
            - text: "Question Formatting"
              href: question-formatting.qmd
            - text: "Custom Questions"
              href: custom-questions.qmd
            - text: "Server Options"
              href: server-options.qmd
            - text: "System Translations"
              href: system-translations.qmd
            - text: "Conditional Control"
              href: conditional-control.qmd
            - text: "External Resources"
              href: external-resources.qmd
            - text: "Reactivity"
              href: reactivity.qmd
            - text: "Redirect"
              href: redirect.qmd
            - text: "Password"
              href: password.qmd
            - text: "Store Data"
              href: store-data.qmd
            - text: "Fetch Data"
              href: fetch-data.qmd
            - text: "Deployment"
              href: deployment.qmd
            - text: "Performance"
              href: performance.qmd
            - text: "Security"
              href: security.qmd
            - text: "Tips"
              href: tips.qmd
    - title: "Demos"
      style: "docked"
      background: light
      contents:
        - text: "Demos"
          href: demos.qmd
        - text: "Question Types"
          href: demos/question-types.qmd
        - text: "Conditional Display"
          href: demos/show-if.qmd
        - text: "Conditional Skip"
          href: demos/skip-if.qmd
        - text: "Conjoint Buttons"
          href: demos/conjoint-buttons.qmd
        - text: "Random Labels"
          href: demos/random-labels.qmd

format:
  html:
    theme:
      light: [flatly, css/theme.scss]
      dark: [darkly, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

execute:
  echo: true
  eval: false
  warning: false
  message: false
code-link: true
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc-location: right
toc: true
