project:
  type: website
  output-dir: _site
  preview:
    port: 5678
    browser: true
  render:
    - "!chunks/"
    - "404.qmd"
    - "about.qmd"
    - "blog/index.qmd"
    - "blog/**/*.qmd"
    - "demos/**/*.qmd"
    - "demos.qmd"
    - "documentation.qmd"
    - "faq.qmd"
    - "features.qmd"
    - "getting-started.qmd"
    - "index.qmd"
    - "installation.qmd"
    - "manuals/**/*.qmd"
  resources:
    - "manuals/"

website:
  title: surveydown.org
  image: images/logo.ico
  favicon: images/logo.ico
  site-url: https://www.surveydown.org
  repo-url: https://github.com/surveydown/website
  back-to-top-navigation: true
  open-graph:
    locale: es_ES
    site-name: https://surveydown.org
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: images/logo.png
    card-style: summary_large_image
    image-width: 150
    image-height: 150
  page-footer:
    background: dark
    center:
      - text: "Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/jhelvy/jhelvy_quarto' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"

  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: about.qmd   
      - text: "Documentation"
        href: documentation.qmd
      - text: "Demos"
        href: demos.qmd
      - text: "Features"
        href: features.qmd
      - text: "{{< fa brands r-project >}} Package"
        href: https://pkg.surveydown.org/
    right:
      - text: "Blog"
        href: blog/index.qmd
      - text: "FAQ"
        href: faq.qmd
      - icon: github
        href: https://github.com/surveydown-dev/surveydown

  sidebar:
    - title: "Documentation"
      style: "docked"
      background: light
      contents:
        - text: "Documentation"
          href: documentation.qmd
        - text: "Getting Started"
          href: manuals/getting-started.qmd
        - text: "Installation"
          href: manuals/installation.qmd
        - text: "Survey Components"
          href: manuals/survey-components.qmd
        - section: "Survey Content"
          contents:
            - text: "Question Types"
              href: manuals/question-types.qmd
            - text: "Question Formatting"
              href: manuals/question-formatting.qmd
            - text: "System Translations"
              href: manuals/system-translations.qmd
            - text: "External Resources"
              href: manuals/external-resources.qmd
        - section: "Server Content"
          contents:
            - text: "Server Options"
              href: manuals/server-options.qmd
            - text: "Conditional Control"
              href: manuals/conditional-control.qmd
            - text: "Reactivity"
              href: manuals/reactivity.qmd
            - text: "Randomization"
              href: manuals/randomization.qmd
            - text: "Custom Questions"
              href: manuals/custom-questions.qmd
            - text: "Redirect"
              href: manuals/redirect.qmd
        - section: "Database"
          contents:
            - text: "Storing Data"
              href: manuals/storing-data.qmd
            - text: "Fetching Data"
              href: manuals/fetching-data.qmd
            - text: "Dashboard"
              href: manuals/dashboard.qmd
        - section: "Other"
          contents:
            - text: "Deployment"
              href: manuals/deployment.qmd
            - text: "Performance"
              href: manuals/performance.qmd
            - text: "Security"
              href: manuals/security.qmd
            - text: "Tips"
              href: manuals/tips.qmd
    - title: "Demos"
      style: "docked"
      background: light
      contents:
        - text: "Demos"
          href: demos.qmd
        - text: "Question Types"
          href: demos/question-types.qmd
        - text: "Conditional Display"
          href: demos/conditional-display.qmd
        - text: "Conditional Skipping"
          href: demos/conditional-skipping.qmd
        - text: "Conjoint Buttons"
          href: demos/conjoint-buttons.qmd
        - text: "Conjoint Tables"
          href: demos/conjoint-tables.qmd
        - text: "Random Labels"
          href: demos/random-labels.qmd
        - text: "Random Labels Preset"
          href: demos/random-labels-preset.qmd
        - text: "Custom Leaflet Map"
          href: demos/custom-leaflet-map.qmd
        - text: "Custom Plotly Chart"
          href: demos/custom-plotly-chart.qmd

format:
  html:
    theme:
      light: [flatly, css/theme.scss]
      dark: [darkly, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

execute:
  echo: true
  eval: false
  warning: false
  message: false
code-link: true
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc-location: right
toc: true
