project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "index.qmd"
    - "about.qmd"
    - "404.qmd"
  resources:
    - "css"

website:
  title: "surveydown.org"
  image: images/logo.png
  site-url: https://www.surveydown.org
  favicon: images/favicon/favicon.ico
  repo-url: https://github.com/surveydown/website
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: true
  open-graph:
    locale: es_ES
    site-name: https://surveydown.org
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: images/logo.png
    card-style: summary  
  navbar:
    right:
      - text: "About"
        href: about.qmd

  page-footer:
    center:
      - text: "Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/jhelvy/jhelvy_quarto' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"
    