project:
  type: website
  output-dir: _site
  preview:
    port: 5678
    browser: true
  render:
    - "!chunks/"
    - "**/*.qmd"

website:
  title: surveydown.org
  image: images/logo.ico
  favicon: images/logo.ico
  site-url: https://www.surveydown.org
  repo-url: https://github.com/surveydown/website
  back-to-top-navigation: true
  open-graph:
    locale: es_ES
    site-name: https://surveydown.org
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: images/logo.png
    card-style: summary_large_image
    image-width: 150
    image-height: 150
  page-footer:
    background: dark
    center:
      - text: "Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/jhelvy/jhelvy_quarto' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"

  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: about.qmd   
      - text: "Documentation"
        href: docs.qmd
      - text: "Templates"
        href: templates.qmd
      - text: "{{< fa brands r-project >}} Package"
        href: https://pkg.surveydown.org/
    right:
      - text: "Blog"
        href: blog/index.qmd
      - text: "FAQ"
        href: faq.qmd
      - icon: github
        href: https://github.com/surveydown-dev/surveydown

  sidebar:
    - title: "Documentation"
      style: "docked"
      background: light
      contents:
        - text: "Documentation"
          href: docs.qmd

        - section: "Survey Basics"
          contents:
            - text: "Getting Started"
              href: docs/getting-started.qmd
            - text: "Basic Components"
              href: docs/basic-components.qmd
            - text: "Features"
              href: docs/features.qmd

        - section: "Survey Design Concepts"
          contents:
            - text: "Conditional Logic"
              href: docs/conditional-logic.qmd
            - text: "External Resources"
              href: docs/external-resources.qmd
            - text: "System Translations"
              href: docs/system-translations.qmd
            
        - section: "Question Development"
          contents:
            - text: "Question Types"
              href: docs/question-types.qmd
            - text: "Question Formatting"
              href: docs/question-formatting.qmd
            - text: "Custom Questions"
              href: docs/custom-questions.qmd
        
        - section: "Logic and Interactivity"
          contents:
            - text: "Server Options"
              href: docs/server-options.qmd
            - text: "Conditional Question Display"
              href: docs/conditional-question-display.qmd
            - text: "Conditional Survey Flow"
              href: docs/conditional-survey-flow.qmd
            - text: "Common Conditions"
              href: docs/common-conditions.qmd
            - text: "Randomization Techniques"
              href: docs/randomization.qmd
            - text: "Reactivity"
              href: docs/reactivity.qmd
            - text: "Redirection"
              href: docs/redirect.qmd
        
        - section: "Data Management"
          contents:
            - text: "Storing Data"
              href: docs/storing-data.qmd
            - text: "Fetching Data"
              href: docs/fetching-data.qmd
            - text: "Dashboard"
              href: docs/dashboard.qmd
        
        - section: "Deployment & Operations"
          contents:
            - text: "Deployment"
              href: docs/deployment.qmd
            - text: "Performance"
              href: docs/performance.qmd
            - text: "Security"
              href: docs/security.qmd
        
        - section: "Recipes & Patterns"
          contents:
            - text: "Tips"
              href: docs/tips.qmd

    - title: "Templates"
      style: "docked"
      background: light
      contents:
        - text: "Templates"
          href: templates.qmd

        - section: "Basic"
          contents:
            - text: "Plain Template"
              href: templates/01_plain_template.qmd
            - text: "Question Types"
              href: templates/02_question_types.qmd
            - text: "Conditional Display"
              href: templates/03_conditional_display.qmd
            - text: "Conditional Skipping"
              href: templates/04_conditional_skipping.qmd

        - section: "Randomization"
          contents:
            - text: "Random Options"
              href: templates/05_random_options.qmd
            - text: "Random Options Predefined"
              href: templates/06_random_options_predefined.qmd

        - section: "Reactivity"
          contents:
            - text: "Reactive Questions"
              href: templates/07_reactive_questions.qmd
            - text: "Reactive drilldown"
              href: templates/08_reactive_drilldown.qmd
            - text: "External Redirect"
              href: templates/09_external_redirect.qmd
            - text: "Live Polling"
              href: templates/10_live_polling.qmd

        - section: "Conjoint"
          contents:
            - text: "Conjoint Buttons"
              href: templates/11_conjoint_buttons.qmd
            - text: "Conjoint Tables"
              href: templates/12_conjoint_tables.qmd

        - section: "Custom"
          contents:
            - text: "Custom Leaflet Map"
              href: templates/13_custom_leaflet_map.qmd
            - text: "Custom Plotly Chart"
              href: templates/14_custom_plotly_chart.qmd

format:
  html:
    theme:
      light: [flatly, css/theme.scss]
      dark: [darkly, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

execute:
  echo: true
  eval: false
  warning: false
  message: false
code-link: true
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc-location: right
toc: true
