project:
  type: website
  output-dir: _site
  preview:
    port: 5678
    browser: true
  render:
    - "!chunks/"
    - "index.qmd"
    - "about.qmd"
    - "documentation.qmd"
    - "getting-started.qmd"
    - "installation.qmd"
    - "password.qmd"   
    - "components.qmd"
    - "questions.qmd"
    - "formatting.qmd"
    - "reactivity.qmd"
    - "config.qmd"
    - "database.qmd"
    - "deployment.qmd"   
    - "fetching-data.qmd"
    - "demos.qmd"
    - "faq.qmd"
    - "404.qmd"
    - "blog/index.qmd"
    - "blog/**/*.qmd"

website:
  title: surveydown.org
  image: images/logo.png
  favicon: images/logo.png
  site-url: https://www.surveydown.org
  repo-url: https://github.com/surveydown/website
  back-to-top-navigation: true
  open-graph:
    locale: es_ES
    site-name: https://surveydown.org
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: images/logo.png
    card-style: summary  
  page-footer:
    background: dark
    center:
      - text: "Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/jhelvy/jhelvy_quarto' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"

  navbar:
    background: primary
    search: true
    left:
      - text: "About"
        href: about.qmd   
      - text: "Documentation"
        href: documentation.qmd   
      - text: "Demos"
        href: demos.qmd
      - text: "{{< fa brands r-project >}} Package"
        href: https://pkg.surveydown.org/
    right:
      - text: "Blog"
        href: blog/index.qmd
      - text: "FAQ"
        href: faq.qmd
      - icon: github
        href: https://github.com/surveydown-dev

  sidebar:
    - title: "Documentation"
      style: "docked"
      background: light
      contents:
        - text: "Documentation"
          href: documentation.qmd
        - text: "Get Started"
          href: getting-started.qmd
        - text: "Install"
          href: installation.qmd
        - text: "Password"
          href: password.qmd
        - text: "Survey Components"
          href: components.qmd
        - text: "Question Types"
          href: questions.qmd
        - text: "Formatting"
          href: formatting.qmd
        - text: "Reactivity"
          href: reactivity.qmd
        - text: "Configuration Options"
          href: config.qmd   
        - text: "Store Data"
          href: database.qmd
        - text: "Deploy"
          href: deployment.qmd
        - text: "Fetch Data"
          href: fetching-data.qmd

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

execute:
  echo: true
  eval: false
  warning: false
  message: false
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc-location: right
toc: true