project:
  type: website
  output-dir: _site
  preview:
    port: 5678
    browser: true
  render:
    - "getting-started.qmd"
    - "index.qmd"
    - "about.qmd"
    - "password.qmd"
    - "installation.qmd"
    - "components.qmd"
    - "questions.qmd"
    - "database.qmd"
    - "deployment.qmd"
    - "formatting.qmd"
    - "config.qmd"
    - "404.qmd"
  resources:
    - "css"

website:
  title: "surveydown.org"
  image: images/logo.png
  site-url: https://www.surveydown.org
  favicon: images/favicon/favicon.ico
  repo-url: https://github.com/surveydown/website
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: true
  open-graph:
    locale: es_ES
    site-name: https://surveydown.org
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: images/logo.png
    card-style: summary  
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        href: about.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "Setting a Password"
        href: password.qmd
      - section: "Documentation"
        contents:
          - text: "Installation"
            href: installation.qmd           
          - section: "Survey Content"
            contents:
              - text: "Survey Components"
                href: components.qmd
              - text: "Question Types"
                href: questions.qmd
              - text: "Formatting Questions"
                href: formatting.qmd
          - text: "Configuration Options"
            href: config.qmd   
          - text: "Database Setup"
            href: database.qmd
          - text: "Deploying Your Survey"
            href: deployment.qmd

page-footer:
  center:
    - text: "Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/jhelvy/jhelvy_quarto' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"

execute:
  echo: true
  eval: false
  warning: false
  message: false
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
toc: true
toc-location: right