name: Render and Deploy Quarto Site
on:
  push:
    branches: main
  schedule:
    - cron: '0 5 * * *'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install brew dependencies
        run: |
          brew install qpdf
          brew install gcc
          brew install libgit2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: true

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install required R packages
        run: |
          install.packages(c("knitr", "rmarkdown", "htmltools", "markdown", "tinytable", "remotes"), dependencies=TRUE)
        shell: Rscript {0}

      - name: Install custom package
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          remotes::install_github("surveydown-dev/surveydown@main")
        shell: Rscript {0}

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}